### ISSUE TITLE
Not Working In Chrome

### ISSUE THREAD

**Issue by metal450** [linusg/owntracks-ui#6]
The web UI wasn't working for me at all in Chrome (the main map div was resolving to 0-height).  This issue: https://stackoverflow.com/questions/33636796/chrome-safari-not-filling-100-height-of-flex-parent

Solution:

    #app > main {
     display: flex;
      flex: 1;
    }

    .vue2leaflet-map{
	height: auto !important;
    }

**Comment by linusg** [comment]
Yeah, I don't quite understand the source of that bug, but I'll try out your workaround ASAP, thanks!
(let's hope for some progress in general this weekend, I really want to get my updated version out)

**Comment by linusg** [comment]
@metal450

Finally fixed as of https://github.com/linusg/owntracks-ui/commit/63bfdec5676f859d70dc70afffbdcfac720b8d97! Sorry for the super slow response time...
Since you seem to have some interest in this project, I can make you a collaborator if you want - I have so many great ideas and so little free time for this project :disappointed:

**Comment by metal450** [comment]
No worries, I had it patched on my end already :)

Thanks for the offer!  Unfortunately my free time is EXTREMELY limited too, so I don't really see myself as being able to invest much into development, now that I got it up & running for my limited purposes :/
